on: push
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: hugo installation
        run:
          sudo apt-get update
          && sudo apt-get install -y hugo
          && sudo hugo
     
      - name: deploy
        uses: actions/deploy-pages@v2
        with:
          folder: public
